services:
  reticulum-meshchat:
    container_name: reticulum-meshchat
    image: ghcr.io/sudo-ivan/reticulum-meshchat:latest
    pull_policy: always
    restart: unless-stopped
    user: "1000:1000"
    # Make the meshchat web interface accessible from the host on port 8000
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - meshchat-config:/config:rw
    # Uncomment if you have a USB device connected, such as an RNode
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
    meshchat-config:
